import type { Metadata } from "next";
import { Krona_One } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const korna = Krona_One({
  weight: '400',
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${korna.className} antialiased`}>
        <ThemeProvider attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
