import type { Metadata } from "next";
import { Krona_One } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavBar } from "@/components/nav-bar";
const korna = Krona_One({
  weight: '400',
  style: "normal",
  display: "swap",
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<ThemeProvider
    attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange
  >
    <html lang="en">
      <NavBar />
      <body className={`${korna.className} antialiased`}>
        {children}
      </body>
    </html></ThemeProvider >
  );
}
