/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MxJgRPSg07u
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Component() {
  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12">
        <div className="order-2 lg:order-1">
          <div className="relative w-full h-auto rounded-lg overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-full bg-[url('/placeholder.svg')] bg-cover bg-center bg-no-repeat" />
            <div className="relative w-full h-0 pb-[75%]">
              <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center bg-[#f1f1f1] rounded-lg">
                <div className="w-[90%] h-[90%] bg-white rounded-lg shadow-lg" />
              </div>
            </div>
          </div>
        </div>
        <div className="order-1 lg:order-2">
          <div className="grid gap-4">
            <div className="flex items-center gap-2">
              <div className="bg-primary px-3 py-1 rounded-full text-xs font-medium text-primary-foreground">
                Web Design
              </div>
              <div className="text-sm text-muted-foreground">February 2024</div>
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold tracking-tight">Acme Inc. Website Redesign</h1>
            <div className="prose max-w-none">
              <p>
                We are thrilled to showcase our latest project, the Acme Inc. website redesign. This comprehensive
                overhaul focused on creating a modern, user-friendly experience that showcases Acme's products and
                services in a visually stunning manner.
              </p>
              <p>
                The new design features a clean and responsive layout, optimized for both desktop and mobile devices.
                The carefully curated color palette and typography create a cohesive and visually appealing brand
                identity, while the intuitive navigation ensures a seamless user experience.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <h3 className="text-lg font-semibold">Desktop Version</h3>
                <div className="relative w-full h-auto rounded-lg overflow-hidden">
                  <div className="absolute top-0 left-0 w-full h-full bg-[url('/placeholder.svg')] bg-cover bg-center bg-no-repeat" />
                  <div className="relative w-full h-0 pb-[75%]">
                    <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center bg-[#f1f1f1] rounded-lg">
                      <div className="w-[90%] h-[90%] bg-white rounded-lg shadow-lg" />
                    </div>
                  </div>
                </div>
              </div>
              <div>
                <h3 className="text-lg font-semibold">Mobile Version</h3>
                <div className="relative w-full h-auto rounded-lg overflow-hidden">
                  <div className="absolute top-0 left-0 w-full h-full bg-[url('/placeholder.svg')] bg-cover bg-center bg-no-repeat" />
                  <div className="relative w-full h-0 pb-[200%]">
                    <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center bg-[#f1f1f1] rounded-lg">
                      <div className="w-[90%] h-[90%] bg-white rounded-lg shadow-lg" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
