import type { Metadata } from "next";
import { Krona_One } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavBar } from "@/components/nav-bar";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
const korna = Krona_One({
  weight: '400',
  style: "normal",
  display: "swap",
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {
    children,
    params: { locale }
  }: {
    children: React.ReactNode;
    params: { locale: string };
  }) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${korna.className} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            <NavBar />
            <div vaul-drawer-wrapper="" className="bg-background">
              {children}
            </div>
          </ThemeProvider>
        </NextIntlClientProvider >

      </body>
    </html >
  );
}
