import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans_Arabic } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavBar } from "@/components/nav-bar";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ReactLenis, useLenis } from "@/lib/lenis";
import { Providers } from "../providers";
const inter = Inter({
  weight: ["400", "500", "600", "700"],
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

const plexArabic = IBM_Plex_Sans_Arabic({
  weight: ["400", "500", "600", "700"],
  style: "normal",
  display: "swap",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages({
    locale
  });

  return (
    <html lang={locale} dir={
      locale === "ar" ? "rtl" : "ltr"
    }>
      <Providers>
        <body
          className={`${locale === "ar" ? plexArabic.className : inter.className} antialiased `}
        >
          {/* <ReactLenis root> */}

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > <NextIntlClientProvider messages={messages} locale={locale}>
              <NavBar />
              <div vaul-drawer-wrapper="" className="bg-background">
                {children}
              </div>
            </NextIntlClientProvider>
          </ThemeProvider>

          {/* </ReactLenis> */}
        </body>
      </Providers>
    </html>
  );
}
